pknu-wap/WABI-FE

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/api/fileUpload.ts
client/src/components/group_detail/FileUploadModal/FileUploadModal.tsx
client/src/components/group_detail/MemberUpdateButton/MemberUpdateButton.tsx
client/src/index.tsx
client/src/pages/GroupDetail/GroupDetail.tsx

- App.tsx에서 기본적으로 세팅되어 있는 React 소개 페이지 관련 컴포넌트들을 지우고 GroupDetail 컴포넌트를 추가하였습니다.
* Notion 링크 : https://www.notion.so/2024-08-23-9c9e73c9726049d8a7baecbc1eb989e3?pvs=4#281e03f3321346cd925c50ba8fd94a23
1. **파일 구조 관련**
- services → api 로 변경했음
- src/pages → 폴더명 페이지 이름으로 하여 만든다. (폴더 안에 관련 CSS, Tsx 들어감)
- src/components/폴더명 페이지 이름/폴더명 페이지에서 사용하는 컴포넌트들
2. mock 서버 만들기 with PostMan - [https://velog.io/@chm0202/Postman으로-Mock-Server-만들기**](https://velog.io/@chm0202/Postman%EC%9C%BC%EB%A1%9C-Mock-Server-%EB%A7%8C%EB%93%A4%EA%B8%B0**)
3. 파일 업로드 없이 파일 전송하는 경우의 예외처리 아직 안 됨 → 추가 예정
- 업로드 성공 이후 처리도 해야할듯
4. BE 팀에게 파일 전송 형태 전달 완료
5. xls 확장자는 어떻게 하는가?
- 코드 컨벤션, typescript의 타입 처리에 대해서 중점적으로 확인 부탁드립니다!

csv, xlsx 확장자 파일 업로드 및 전송 기능

---

client/src/components/event_detail/CheckInTable/CheckInTable.tsx

체크인 현황 페이지에 있는 테이블에서 각 행을 <code>index</code>로 구분했었는데, <code>id</code>로 바꾸었습니다.
```typescript
{students.length > 0 ? (
students.map((row,index) => (
<tr key={index}>
<Styled.ThData>{row.id}</Styled.ThData>
<Styled.ThData>{row.name}</Styled.ThData>
<Styled.ThBorder>{row.group}</Styled.ThBorder>
<Styled.ThBorder>
{eventStudentStatusImage(row.eventStudentStatus)}
</Styled.ThBorder>
<Styled.ThBorder>{row.checkInTime}</Styled.ThBorder>
</tr>
```
리액트에서 <code>map()</code>으로 컴포넌트 호출시 <code>key</code>를 <code>index</code>로 두면 중간에 아이템이 추가되고 삭제될 때 <code>key</code>가 같아지는 경우가 발생하기 때문에 에러가 발생할 수 있습니다.
그래서 각 <code>row</code> 가 고유한 값을 가지도록 <code>id</code>로 전달하는 방식으로 바꾸었습니다.
```typescript
{students.length > 0 ? (
students.map((row) => (
<tr key={row.id}>
<Styled.ThData>{row.id}</Styled.ThData> …
```

체크인현황 테이블 key변경

---

client/src/components/EventGroupSwitcher/CreateEventForm/CreateEventForm.tsx
client/src/components/EventGroupSwitcher/CreateGroupForm/CreateGroupForm.tsx
client/src/components/EventGroupSwitcher/FormSaveButton/FormSaveButton.styles.ts
client/src/components/EventGroupSwitcher/FormSaveButton/FormSaveButton.tsx
client/src/components/common/Button/Button.styles.ts
client/src/components/common/Button/Button.tsx
client/src/components/common/CommonFormLayout/CommonFormLayout.styles.ts
client/src/components/common/CommonFormLayout/CommonFormLayout.tsx
client/src/components/common/InputField/InputField.styles.ts
client/src/components/common/InputField/InputField.tsx

#38 에 있는 Hifi 스타일을 그대로 만들어야 했습니다.
<details>
<summary>InputField.tsx</summary>
```js
import React from 'react';
import * as Styled from 'components/common/InputField/InputField.styles';
interface InputFieldProps {
label: string;
placeholder?: string;
required: boolean;
type?: string;
value?: string | number;
onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
}
const InputField = ({
label,
placeholder,
required,
type = 'text',
value,
onChange,
}: InputFieldProps) => {
return (
<Styled.InputContainer>
<Styled.Label>
{label} {required && <Styled.Required>*</Styled.Required>}
</Styled.Label>
<Styled.Input
type={type}
placeholder={placeholder}
required={required}
value={value}
onChange={onChange}
/>
</Styled.InputContainer>
);
};
export default InputField;
```
</details>
<details> …

[feature] 이벤트/그룹 생성 폼 스타일 적용

---

client/src/api/group.ts
client/src/components/EventGroupSwitcher/CreateEventForm/CreateEventForm.tsx
client/src/components/EventGroupSwitcher/CreateGroupForm/CreateGroupForm.tsx
client/src/pages/EventGroupSwitcher/EventGroupSwitcher.tsx
client/src/types/eventTypes.ts
client/src/types/groupTypes.ts

이전 event API 연동 PR과 거의 같은 형태입니다.
그룹 생성, 수정, 삭제, 조회 api 제작 완료
- axios를 활용해서 생성, 수정, 삭제, 단일 조회 api를 제작했습니다.
- createGroup 함수 : 그룹 정보를 백엔드에 전달해 이벤트 생성하는 함수
- updateGroup 함수 : 수정한 그룹 정보를 백엔드에 전달해 이벤트 수정하는 함수
- getGroupById 함수 : 그룹 정보를 조회해서 데이터를 받아오는 함수
- deleteGroup 함수 : 그룹를 삭제하는 함수
<br />
1. 그룹 생성, 수정, 조회, 삭제 api 연결
- handleSave 완선
- handleChange 완성
- handleDelete 완성
<br />
2. 그룹 정보 useState 상태 처리
```js
const [groupFormData, setGroupFormData] = useState({
bandName: '',
bandMemo: '',
});
```
<br />
3. CreateGroupForm 컴포넌트 props로 `bandId` 전달 받음
- bandId가 있다면 수정 폼 + 조회
- bandId가 없다면 개설 폼
<br />
4. adminId 추가
- api 전송시에 같이 들어갈 파라미터
-  adminId는 전역적으로 처리해야해서 전역적으로 관리해줘야 할듯
```js
const adminId = 1; //추후 로그인 정보에 맞는 adminId로 적용해야함
```
<br />
5. API 연결을 위해 eventId의 props를 number로 바꾸어줌
<br />
그룹 API 및 …

 [feature] 그룹 생성, 수정, 삭제 기능 API 연동 완료

---

client/src/components/common/Title/Title.tsx
client/src/components/event_detail/CheckInGroup/CheckInGroup.tsx
client/src/components/event_detail/CheckInStatus/CheckInStatus.styles.ts
client/src/components/event_detail/CheckInStatus/CheckInStatus.tsx
client/src/components/event_detail/CheckInTable/CheckInTable.tsx
client/src/hooks/useCheckInStudent.tsx
client/src/pages/EventDetail/EventDetail.styles.ts
client/src/pages/EventDetail/EventDetail.tsx
client/src/types/eventTypes.ts

- 이벤트에 참여하는 학생들의 그룹들을 커스텀 훅 대신 이벤트 데이터를 API로 받아오게 바꾸었습니다.
```js
// EventDetail.tsx
useEffect(() => {
if (eventId !== 'No Event ID') {
const adminId = 1;
const eventIdNumber = parseInt(eventId, 10);
getEventById(eventIdNumber, adminId).then(response => {
setGroups(response.data.bands);
});
}
}, []);
```
-  몇 명이 현재 체크인 했는지 현황을 보여주는 컴포넌트를 생성하였습니다.
```js
// ChekcInStatus.tsx
interface CheckInStatusProps {
eventId: string;
adminId: number;
}
const CheckInStatus = ({eventId, adminId}: CheckInStatusProps) => {
const [checkInCount, setCheckInCount] = useState<number>(0);
const [totalCount, setTotalCount] = useState<number>(0);
const loadCheckInStatus = () => {
const eventIdToNumber = parseInt(eventId, 10);
getEventById(eventIdToNumber, adminId).then(response => {
const checkInStatus = …
```

[feature] Event Detail 페이지 Event 이름 및 그룹 리스트 받아오기

---

client/src/hooks/useCheckInEvent.tsx

- 체크인 현황 로드시간 변경했습니다
```typescript
useEffect(() => {
const interval = setInterval(() => {
LoadCheckInStudent();
console.log('로드 그룹');
// console.log(groups);
}, 1000);
```
```
```

[hotfix] 이벤트 체크인 현황 로드시간 변경

---

client/src/api/fileUpload.ts
client/src/api/loadGroupMemberList.ts
client/src/api/manualUpload.ts
client/src/components/GroupDetail/FileUploadModal/FileUploadModal.styles.ts
client/src/components/GroupDetail/FileUploadModal/FileUploadModal.tsx
client/src/components/GroupDetail/ManualUploadModal/ManualUploadModal.tsx
client/src/components/GroupDetail/ManualUploadModal/steps/OptionalStep.styles.ts
client/src/components/GroupDetail/ManualUploadModal/steps/OptionalStep.tsx
client/src/components/GroupDetail/ManualUploadModal/steps/RequiredStep.styles.ts
client/src/components/GroupDetail/ManualUploadModal/steps/RequiredStep.tsx
client/src/components/GroupDetail/MemberUpdateButton/MemberUpdateButton.tsx
client/src/components/common/Button/Button.styles.ts
client/src/components/common/GroupMemberList/GroupMember.tsx
client/src/components/common/GroupMemberList/GroupMemberList.tsx
client/src/components/common/ModalFrame/ModalFrame.styles.ts
client/src/components/common/ModalFrame/ModalFrame.tsx
client/src/pages/GroupDetail/GroupDetail.styles.ts
client/src/pages/GroupDetail/GroupDetail.tsx
client/src/types/studentTypes.ts

- 전체적인 UI 구현하였습니다. (밑의 사진 참고)
**- SearchBox 공통컴포넌트를 이용하여 검색 기능을 구현하였습니다.**
```typescript
<Styled.Wrapper>
<Header/>
<Styled.InnerLayout>
<div>
<FileUploadModal modalStateValue={fileUploadModalStateValue}/>
<ManualUploadModal modalStateValue={manualUploadModalStateValue}/>
<Title titleText={'Group Name'} subTitleText={'그룹 메모'}/>
<SearchAndButtonFrame>
<SearchBox filterTextChange={setListFilterText}/>
<div>
{/*Todo 자동추가 / 수동추가 버튼을 Button 컴포넌트 활용해서 나누기*/}
<MemberUpdateButton onClick={openFileUploadModal} isFileUpload={true}/>
<MemberUpdateButton onClick={openManualUploadModal} isFileUpload={false}/>
</div>
</SearchAndButtonFrame>
<div>
<GroupMemberList groupId={groupId} filterText={listFilterText} />
</div>
</div>
</Styled.InnerLayout>
</Styled.Wrapper>
```
**-  GroupMemeberList에 검색 키워드에 맞게 …

[Feature] group detail 페이지 UI 완성

---

client/src/components/EventAndGroupList/EventCard/EventCard.styles.ts
client/src/components/EventAndGroupList/GroupCard/GroupCard.styles.ts

GroupCard와 EventCard에 hover시에 크기가 약간 커지고 그림자가 생깁니다.
크기 전환 시간은 0.2초동안으로 설정해서 부드럽습니다!
https://github.com/user-attachments/assets/61d92b82-d4ae-4eed-9fc4-6afa099a71ae
```css
transition:
transform 0.2s ease-in-out,
box-shadow 0.2s ease-in-out;
&:hover {
transform: scale(1.05);
box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1);
}
```
```
```

[feature] GroupCard, EventCard hover 스타일 적용

---

client/src/components/EventAndGroupList/EventCard/EventCard.styles.ts
client/src/components/EventAndGroupList/EventCardList/EventCardList.styles.ts
client/src/components/EventAndGroupList/GroupCard/GroupCard.styles.ts
client/src/components/EventAndGroupList/GroupCard/GroupCard.tsx
client/src/components/EventAndGroupList/GroupCardList/GroupCardList.styles.ts
client/src/components/EventAndGroupList/ParticipateProgress/ParticipateProgress.styles.ts
client/src/components/common/CommonFormLayout/CommonFormLayout.styles.ts
client/src/index.css
client/src/pages/EventAndGroupList/EventAndGroupList.styles.ts

- 🔨이벤트 카드의 width는 줄이고 height를 늘렸습니다
- 🔨이벤트 카드리스트 grid 크기를 조정했습니다
- 🔨그룹 카드의 width는 줄이고 height를 늘렸습니다
- 🔨그룹 카드리스트 grid 크기를 조정했습니다
- 스크롤 생성으로 첫렌더링시에 버벅거리는게 있는듯 합니다
```
```

[fix] EventAndGroupList Tab 아랫부분 UI 수정

---

client/src/App.tsx
client/src/components/Authentication/SignInForm/SignInForm.styles.ts
client/src/components/Authentication/SignInForm/SignInForm.tsx
client/src/components/Authentication/SignUpForm/SignUpForm.styles.ts
client/src/components/Authentication/SignUpForm/SignUpForm.tsx
client/src/components/common/CommonFormLayout/CommonFormLayout.styles.ts
client/src/components/common/CommonFormLayout/CommonFormLayout.tsx
client/src/pages/SignIn/SignIn.styles.ts
client/src/pages/SignIn/SignIn.tsx
client/src/pages/SignUp/SignUp.styles.ts
client/src/pages/SignUp/SignUp.tsx

**1. 회원가입, 로그인 입력폼 컴포넌트 생성**
components -> Authentication -> SignInForm
components -> Authentication -> SignUpForm
</br>
**2. 회원가입시 아이디, 비밀번호 검증 로직 추가**
- 이메일은 자동으로 html에서 검증해줌
</br>
**3. pages폴더 안에 SignIn.tsx, SignUp.tsx 각각 페이지 생성****
</br>
**4. App.tsx에 SignIn, SignUp 페이지 라우팅 경로 추가**
</br>
**5. CommonFormLayout 스타일 수정**
</br>
1. API 연결 시켜야하는 부분에 주석 남겨놓았음
2. 추후 헤더에 로그인 정보 나오게 수정해야함
3. 이메일 검증은 html input 태그에서 해주는데 그래도 추가적인 에러 메세지 필요할듯
4. 비밀번호 조건 2번, 3번이 이해가 잘안됨
-> 특수문자는 필수, 그럼 조건 2번 특수문자 하나 썼으니까 더이상 대문자, 숫자 고려하지 않아도 되는건가?
```
```

[feature] 관리자 로그인, 회원가입 UI 제작

---

client/src/api/sendToServer.ts
client/src/components/QrCheckIn/QrScan.tsx
client/src/utils/resetQrScanner.ts

```typescript
const resetQrScanner = (
setQrScanned: React.Dispatch<React.SetStateAction<boolean>>,
onScanResult: (
message: string,
messageColor: string,
qrColor: string,
) => void,
setNextScanned: React.Dispatch<React.SetStateAction<number>>,
delay: number = 1500,
) => {
setTimeout(() => {
setQrScanned(false);
onScanResult(
'QR CODE를 화면의 사각형 안에 맞춰주세요.',
'black',
'lightgray',
);
setNextScanned(prevKey => prevKey + 1);
}, delay);
};
export default resetQrScanner;
```
- qr 인식 후 재인식을 위해 리셋하는 코드를 utils로 분리했습니다.
```typescript
.catch(error => {
const errorMessage = error.response.data.message;
if (errorMessage === '이미 체크인 했습니다.') {
onScanResult('이미 체크인 했습니다', '#FF7078', '#FF7078');
setQrScanned(true);
}
resetQrScanner(setQrScanned, onScanResult, setNextScanned);
});
```
- 기존에 에러를 잡을 때 재인식 로직이 …

[refactor] 에러 시 QR 재인식 안되는 문제

---

client/src/components/QrCheckIn/QrScan.tsx

- qr 성공 시 성공메세지를 1.5초간 유지하기 위해 <code>setTimeout</code>으로<code>setQrScanned</code>를 감싸주었습니다.
- 성공 시에도 재인식을 위해 utils에 있는 <code>resetQrScanner</code>를 추가했습니다.
```
```

[fix] 정상 참석 시 딜레이 추가

---

client/package-lock.json
client/package.json
client/src/components/EventAndGroupList/CreateEventForm/CreateEventForm.tsx

- 참여 그룹 선택을 위한 Select 컴포넌트 추가.
- MultiValue 타입을 사용해 다중 선택 기능 구현.
- 그룹 리스트를 동적으로 불러와 Select 옵션으로 매핑.
- Label 컴포넌트를 styled-components로 변경하여 스타일 통일.
- htmlFor 속성을 유지해 접근성 개선.
```
```

[feature]참여 그룹 선택 기능 추가 및 Label 스타일 개선

---

client/package-lock.json
client/package.json
client/src/components/EventAndGroupList/CreateEventForm/CreateEventForm.tsx
client/src/components/QrCheckIn/QrScan.tsx

[release] v0.2.1

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/api/apiClient.ts
client/src/api/event.ts
client/src/api/group.ts
client/src/api/loadEventList.ts
client/src/api/loadGroupList.ts
client/src/api/logIn.ts
client/src/components/Authentication/SignInForm/SignInForm.tsx
client/src/components/Authentication/SignUpForm/SignUpForm.tsx
client/src/components/EventAndGroupList/CreateEventForm/CreateEventForm.tsx
client/src/components/EventAndGroupList/CreateGroupForm/CreateGroupForm.tsx
client/src/components/common/Header/Header.tsx
client/src/components/event_detail/CheckInStatus/CheckInStatus.tsx
client/src/pages/EventDetail/EventDetail.tsx
client/src/queries/eventQueries/useGetEvent.ts
client/src/queries/groupQueries/useGetGroup.ts

[feat] 회원가입,로그인 기능 완성

---

client/src/api/apiClient.ts
client/src/api/logIn.ts
client/src/api/signUp.ts

1. 서버주소가 https에서 http로 변경되었습니다.
2. 쿠키 secure설정을 true로 하여 프로덕션모드에서 오류가 나지 않게 했습니다. 
```
```

[fix] 서버 주소 임시변경 및 쿠기설정 변경

---

client/src/api/apiClient.ts
client/src/api/logIn.ts
client/src/api/signUp.ts

서버주소를 다시 https로 복구하였습니다.
```
```

[fix] https로 원상복구

---

client/src/api/apiClient.ts
client/src/api/logIn.ts
client/src/api/signUp.ts

[release] v0.2.3

---

client/public/_redirects
client/src/api/apiClient.ts
client/src/api/logIn.ts
client/src/api/signUp.ts

1. http로 다시 변경
2. 리다이렉션 파일 프록시설정 추가
```
```

[fix] 서버주소 http 복구 및 리다이렉션 설정추가

---

client/public/_redirects
client/src/api/apiClient.ts
client/src/api/logIn.ts
client/src/api/signUp.ts

[release] v0.2.4

---

client/src/api/apiClient.ts
client/src/api/logIn.ts
client/src/api/signUp.ts

[feature] 서버 주소 환경변수로 처리

---

client/public/_redirects
client/src/api/apiClient.ts
client/src/api/logIn.ts
client/src/api/signUp.ts

[realease] v0.2.5

---

client/src/api/apiClient.ts

[release] v0.2.6

---

client/src/api/apiClient.ts

[realease] v0.2.7
